"""
SQLAlchemy model for form extractions generated by AI.
"""

import uuid

from sqlalchemy import (
    Column,
    TIMESTAMP,
    ForeignKey,
    text,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from data_service.constants.constants import TableName
from data_service.models.base import Base


class FormExtractions(Base):
    """Stores AI-extracted data for submitted forms."""

    __tablename__ = TableName.FORM_EXTRACTIONS.value

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    submission_id = Column(
        UUID(as_uuid=True), ForeignKey("sage_ai_submissions.id"), nullable=False
    )
    form_id = Column(
        UUID(as_uuid=True), ForeignKey("sage_ai_submission_forms.id"), nullable=False
    )
    extracted_data = Column(JSONB, nullable=False)
    created_at = Column(TIMESTAMP, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = Column(
        TIMESTAMP,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=text("CURRENT_TIMESTAMP"),
    )

    def __repr__(self):
        return (
            f"<FormExtractions(id={self.id}, submission_id={self.submission_id}, "
            f"form_id={self.form_id})>"
        )

    def to_dict(self):
        """Convert model instance to dictionary."""
        return {
            "id": str(self.id),
            "submission_id": str(self.submission_id),
            "form_id": str(self.form_id),
            "extracted_data": self.extracted_data,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
