INSERT INTO public.sage_ai_questions (id, question, question_type, prompt)
VALUES 
    ('D-Q01', 'Provide a short title for your solution', 'Text', ''),
    ('D-Q02', 'Who are the primary users of your solution and what problem are you trying to solve?', 'Text', ''),
    ('D-Q03', 'How does your solution address the problem?', 'Text', ''),
    ('D-Q04', 'What does success look like for your solution?', 'Text', '');

INSERT INTO public.sage_ai_questions
(id, question, question_type, prompt) VALUES
('L-Q1', 'Report a Privacy Concern?', 'Radio', ''),
('L-Q2', 'How can we help?', 'Radio', ''),
('L-Q3', 'What can we help with?', 'Radio', ''),
('L-Q4', 'Privacy Review needed:', 'Radio', ''),
('L-Q5', 'DETAILS for Review:', 'Text (Long Text)', ''),
('L-Q6', 'Which Business Area / Corporate Leadership is ultimately accountable for this issue / project / initiative / concern?', 'Dropdown', ''),
('L-Q7', 'Please upload', 'File Upload', ''),
('L-Q8', 'What led you to this Privacy Form today?', 'Radio', '');


INSERT INTO public.sage_ai_questions 
(id, question, question_type, prompt) VALUES
('AI-Q3', 'What scope has changed since the previous submission? (select all that apply)', 'Multi Selection', ''),
('AI-Q4', 'Explain your changes', 'Text', ''),
('AI-Q5', 'What is the title of the System?', 'Text', ''),
('AI-Q6', 'Provide an overview of the solution', 'Text', ''),
('AI-Q7', 'What is the value proposition for this solution?', 'Text', ''),
('AI-Q8', 'Which organization will sponsor the System?', 'Dropdown', ''),
('AI-Q9', 'Are you planning to implement a vendor product as part or all of this system?', 'Radio', ''),
('AI-Q10', 'Which vendor(s)?', 'Multi Selection', ''),
('AI-Q11', 'What product(s)?', 'Text', ''),
('AI-Q12', 'Briefly describe the users of the system, what they will be using it for, and what problem it will solve for them', 'Text', ''),
('AI-Q13', 'Where will you deploy your System? (Select all that apply)', 'Multi Selection', ''),
('AI-Q14', 'Who is the audience of this system? (Select all that apply)', 'Multi Selection', ''),
('AI-Q15', 'Do you have any additional technical information to provide?', 'Radio', ''),
('AI-Q16', 'What is the maturity of the System?', 'Dropdown', ''),
('AI-Q17', 'Does the System process any of the following data? (Select all that apply)', 'Multi Selection', ''),
('AI-Q18', 'What is the highest data classification for processed data?', 'Dropdown', ''),
('AI-Q19', 'Is any of this data used for training the model?', 'Dropdown', ''),
('AI-Q20', 'Describe the Data Needed', 'Text', ''),
('AI-Q21', 'Does the AI Functionality of the system do any of the following? (Select all that apply)', 'Multi Selection', ''),
('AI-Q22', 'Is the AI system output reviewed by a human before it is used', 'Dropdown', ''),
('AI-Q23', 'Please explain (What is the impact if the AI system output is wrong?)', 'Text', ''),
('AI-Q24', 'Which AI platforms/tech will be used?', 'Multi Selection', ''),
('AI-Q25', 'AI Models', 'Multi Selection', ''),
('AI-Q26', 'Open Source Models', 'Multi Selection', ''),
('AI-Q27', 'Does the AI/ML use continuous learning?', 'Radio', ''),
('AI-Q28', 'Privacy Request Identifier', 'Text', ''),
('AI-Q29', 'SAE Review Number', 'Text', ''),
('AI-Q30', 'WwTP review', 'Text', ''),
('AI-Q31', 'Add attachments', 'File Upload', ''),
('AI-Q32', 'Other Vendor', 'Text', ''),
('AI-Q33', 'Other Region', 'Text', ''),
('AI-Q34', 'Other Audience', 'Text', ''),
('AI-Q35', 'Other Platform', 'Text', ''),
('AI-Q36', 'Other Models', 'Text', ''),
('AI-Q37', 'Other Open Source Models', 'Text', '')
ON CONFLICT (id) DO UPDATE SET
  question = EXCLUDED.question,
  question_type = EXCLUDED.question_type,
  prompt = EXCLUDED.prompt;

INSERT INTO public.sage_ai_questions
(id, question, question_type, prompt) VALUES
('R-Q1', 'Select Request to Clone (if applicable):', 'Dropdown', ''),
('R-Q2', 'What is the Title of Request?', 'Text', ''),
('R-Q3', 'Additional Collaborator, if any', 'Text', ''),
('R-Q4', 'What is the Request Type?', 'Dropdown', ''),
('R-Q5', 'Provide the location for this request.', 'Text', ''),
('R-Q6', 'Describe exactly the decision being requested?', 'Text', ''),
('R-Q7', 'please provide a description of your initiative vendor or system what is the business value', 'Text', ''),
('R-Q8', 'Estimated timeline for completion and requested resources.', 'Text', ''),
('R-Q9', '(Select all that apply) Who is the use case audience?', 'Multi-selection', ''),
('R-Q10', 'Describe use case in detail.', 'Text', ''),
('R-Q11', 'What new/different capability will this use case deliver?', 'Text', ''),
('R-Q12', 'List third parties involved in executing this use case. Please choose "Other" if the third-party name is not listed or choose "N/A" if no third party is involved.', 'Multi-selection', ''),
('R-Q13', 'Indicate which assessments have already been completed for the Third Party(ies) provided above.', 'Multi-selection', ''),
('R-Q14', 'List internal data source and type and/or third-party vendors and purchased datasets that are used with this use case.', 'Text', ''),
('R-Q15', 'List each entity providing Personal Information (PI)elements (e.g., name, address, etc.) to/from Lilly including third parties.', 'Text', ''),
('R-Q16', 'Are there contractual limitations in relation to processing of data associated with PI elements referenced in question above?', 'Text', ''),
('R-Q17', 'What permission is being relied on by the third-party to share certain data with Lilly?', 'Text', ''),
('R-Q18', 'How is the third-party collecting the specific PI data elements?', 'Dropdown', ''),
('R-Q19', 'Specify the geo location of the third-party data server for this use case. Example: US-Ohio', 'Text', ''),
('R-Q20', 'Do any of the data sources involve data from a Patient Support Program?', 'Dropdown', ''),
('R-Q21', 'Provide DOUG Approval ID', 'Text', ''),
('R-Q22', 'Identify the Business Application in the Enterprise CMDB where appropriate', 'Text', ''),
('R-Q23', 'Additional Information', 'Text', ''),
('R-Q24', 'Add attachments', '', '');


INSERT INTO public.sage_ai_questions
(id, question, question_type, prompt) VALUES
('S-Q1',  'Title',  'Text', ''),
('S-Q2',  'Business Domain',  'Dropdown', ''),
('S-Q3',  'Please provide a description of your initiative, vendor or system. What is the business value?',  'Text', ''),
('S-Q4',  'If this has been reviewed by SAE previously, please include SAE ticket number below (integer only). If you''re not sure, leave blank.',  'Text', ''),
('S-Q5',  'Does this initiative, vendor or system use AI?',  'Dropdown', ''),
('S-Q6',  'If so, was this previously entered into the AI Registry?',  'Text', ''),
('S-Q7',  'Who (by Lilly email) must remain informed about the progress of this ticket, separated by comma?',  'Text', ''),
('S-Q8',  'Who is the technical lead or IT contact responsible for this project?',  'Text', ''),
('S-Q9',  'In what development phase is the initiative, vendor or system?',  'Dropdown', ''),
('S-Q10', 'Will this be completely separate from our production systems and networks?',  'Dropdown', ''),
('S-Q11', 'The POC will run 90 days or less',  'Dropdown', ''),
('S-Q12', 'Will fewer than 20 people total have access to test this solution?',  'Dropdown', ''),
('S-Q13', 'Is the primary goal to evaluate/test specific functionality before making a larger investment decision?',  'Dropdown', ''),
('S-Q14', 'ServiceNow CMDB CI ID',  'Text', ''),
('S-Q15', 'When is the production delivery date or other key milestone for this initiative, vendor or system?',  'Date', ''),
('S-Q16', 'Where and how is this hosted?',  'Dropdown', ''),
('S-Q17', 'List any cloud accounts this will use (development, testing, production environments)', 'Text', ''),
('S-Q18', 'Provide details on the hosting infrastructure.', 'Text', ''),
('S-Q19', 'Web application URL', 'Text', ''),
('S-Q20', 'Links to code repositories [All GitHub repositories, frontend,backend, etc.] and PLEASE INCLUDE BRANCH TO BE SCANNED (if there are no repositories that apply, mark ''N/A'')', 'Text', ''),
('S-Q21', 'Who will use/access the application?', 'Dropdown', ''),
('S-Q22', 'Explain how users interact with the system, what kinds of roles will exist, and what kinds of data/transactions each user type will conduct in the application.', 'Text', ''),
('S-Q23', 'Does this use Lilly''s standard login system (SSO/Entra ID) for ALL logins?', 'Dropdown', ''),
('S-Q24', 'Will this connect to or share data with other systems or services?', 'Text', ''),
('S-Q25', 'What kind of data will transact through this platform? Provide some samples or examples wherever possible.', 'Text', ''),
('S-Q26', 'Will this project use ONLY test/synthetic/public data (no real customer, patient, or financial data)?', 'Dropdown', ''),
('S-Q27', 'Are there any relevant regulatory or compliance considerations? For example, GDPR, PCI, SOX, HIPAA.', 'Text', ''),
('S-Q28', 'Are privacy, legal, and other appropriate and relevant compliance functions aware of this project or use case? Have they explicitly approved? Did they express any concerns or requirements?', 'Text', ''),
('S-Q29', 'Are there any third parties involved that provide or leverage technology that processes Lilly data?', 'Dropdown', ''),
('S-Q30', 'List all vendor names, products, and websites', 'Text', ''),
('S-Q31', 'Explain the third party''s role in the project', 'Text', ''),
('S-Q32', 'Aravo Engagement ID', 'Text', ''),
('S-Q33', 'Does the third party access Lilly''s systems or services?', 'Text', ''),
('S-Q34', 'Add attachments', 'File upload', ''),
('S-Q35', 'Does the system store, transact or otherwise interact with PHI?', 'Dropdown', ''),
('S-Q36', 'Does the system store, transact or otherwise interact with PI or SPI?', 'Dropdown', ''),
('S-Q37', 'How is sensitive data protected?', 'Dropdown', ''),
('S-Q38', 'Does the platform transact payments or collect a user''s financial information?', 'Dropdown', ''),
('S-Q39', 'Does the platform store, access, or transact Lilly financial data?', 'Dropdown', ''),
('S-Q40', 'Does the platform store, access, or transact Lilly intellectual property, non-public research, or other company confidential data?', 'Dropdown', ''),
('S-Q41', 'Explain why Lilly SSO is not used for all logins.', 'Text', '');

INSERT INTO public.sage_ai_questions
(id, question, question_type, prompt) VALUES
('W-Q1', 'Engagement Name', 'Text', ''),
('W-Q2', 'Engagement Owner', 'Dropdown', ''),
('W-Q3', 'Products/Services/Capabilities Description', 'Text', ''),
('W-Q4', 'Will this engagement include development of an external-facing website or mobile app?', 'Dropdown', ''),
('W-Q5', 'Commodity code(s)', 'Multi-selection', ''),
('W-Q6', 'Anticipated Engagement Expiration', 'Date Picker', ''),
('W-Q7', 'Engagement services country location(s). Select all that apply.', 'Multi-selection', ''),
('W-Q8', 'Engagement Locations (Additional Location Address)', 'Add List', ''),
('W-Q9', 'Job Title', 'Text', ''),
('W-Q10', 'First Name', 'Text', ''),
('W-Q11', 'Last Name', 'Text', ''),
('W-Q12', 'Email', 'Text', ''),
('W-Q13', 'Telephone Number', 'Text', ''),
('W-Q14', 'Have you obtained approval via the Global Customer Office Risk Registry process?', 'Radio', ''),
('W-Q15', 'Vendor Name', 'Dropdown', '');
-- ('W-Q14', 'Anti corruption - Engagement services country location(s)', 'Multi-selection', ''),
-- ('W-Q15', 'Anti corruption - What is the CPI for the countries from which the third party is providing services?', 'Text', ''),
-- ('W-Q16', 'Information Security - Is the third party processing confidential and/or personal information (collectively "Information")?', 'Dropdown', ''),
-- ('W-Q17', 'Information Security - Will the third party be hosting data on Lilly''s behalf?', 'Dropdown', ''),
-- ('W-Q18', 'Information Security - Will the third party be developing websites?', 'Dropdown', ''),
-- ('W-Q19', 'Information Security - Will the third party be developing software?', 'Dropdown', ''),
-- ('W-Q20', 'Information Security - Will the third party require a network connection to Lilly?', 'Dropdown', ''),
-- ('W-Q21', 'Information Security - Will the third party require access to Lilly systems?', 'Dropdown', ''),
-- ('W-Q22', 'Information Security - What level of enterprise impact could an information breach or cyber-event (e.g. malware, ransomware, virus, etc.) at the Third Party have to Lilly (enterprise-wide)? Impact areas are: *Damage that could result to company operations or to an individual *Damage that could impact Lilly''s reputation or public image *Loss of customer, employee, shareholder, or business partner confidence *Loss or disclosure of highly-sensitive Confidential Information (CI), such as trade secret, patent, or other intellectual property protection *Negative impact to the successful development or launch of a Lilly product or indication *Loss of revenue or profitability, including fines or penalties. *Causes short or long term negative impact in Lilly stock value', 'Text', ''),
-- ('W-Q23', 'Privacy - Is the third party processing Personal Information?', 'Dropdown', ''),
-- ('W-Q24', 'Does the third party develop[software], support or manage information, systems, or services that could impact any of the following?(Note: Product in this instance relates to a pharmaceutical product or materials/devices needed to correctly administer the pharmaceutical product)?', 'Text', '');

-- WWTP New Vendor Form Questions (WNV)
INSERT INTO public.sage_ai_questions (id, question, question_type, prompt)
VALUES
    ('WNV-Q1',  'Third Party Name', 'Text', ''),
    ('WNV-Q2',  'Third Party Type', 'Dropdown', ''),
    ('WNV-Q3',  'Address Line 1', 'Text', ''),
    ('WNV-Q4',  'Address Line 2', 'Text', ''),
    ('WNV-Q5',  'Address Line 3', 'Text', ''),
    ('WNV-Q6',  'Country', 'Dropdown', ''),
    ('WNV-Q7',  'City', 'Text', ''),
    ('WNV-Q8',  'State / Region / Province', 'Dropdown', ''),
    ('WNV-Q9',  'Postal Code', 'Text', ''),
    ('WNV-Q10', 'Third Party web address', 'Text', ''),
    ('WNV-Q11', 'SAP ID', 'Text', ''),
    ('WNV-Q12', 'Job Title', 'Text', ''),
    ('WNV-Q13', 'First Name', 'Text', ''),
    ('WNV-Q14', 'Last Name', 'Text', ''),
    ('WNV-Q15', 'Email', 'Text', ''),
    ('WNV-Q16', 'Telephone Number', 'Text', ''),
    ('WNV-Q17', 'Relationship Owner', 'Dropdown', ''),
    ('WNV-Q18', 'Functional Owner', 'Dropdown', ''),
    ('WNV-Q19', 'Engagement Name', 'Text', ''),
    ('WNV-Q20', 'Engagement Owner', 'Dropdown', ''),
    ('WNV-Q21', 'Products/Services/Capabilities Description', 'Text', ''),
    ('WNV-Q22', 'Will this engagement include development of an external-facing website or mobile app?', 'Dropdown', ''),
    ('WNV-Q23', 'Commodity code(s)', 'Multi-selection', ''),
    ('WNV-Q24', 'Anticipated Engagement Expiration', 'Date Picker', ''),
    ('WNV-Q25', 'Engagement services country location(s). Select all that apply.', 'Multi-selection', ''),
    ('WNV-Q26', 'Engagement Locations (Additional Location Address)', 'Add List', ''),
    ('WNV-Q27', 'Job Title', 'Text', ''),
    ('WNV-Q28', 'First Name', 'Text', ''),
    ('WNV-Q29', 'Last Name', 'Text', ''),
    ('WNV-Q30', 'Email', 'Text', ''),
    ('WNV-Q31', 'Telephone Number', 'Text', ''),
    ('WNV-Q32', 'Have you obtained approval via the Global Customer Office Risk Registry process?', 'Radio', '');
ON CONFLICT (id) DO UPDATE SET
  question = EXCLUDED.question,
  question_type = EXCLUDED.question_type,
  prompt = EXCLUDED.prompt;