"""create rps status table

Revision ID: 1cbe5c612473
Revises: a79303c9d82f
Create Date: 2025-11-12 15:23:30.951506

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cbe5c612473"
down_revision: Union[str, None] = "a79303c9d82f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sage_ai_rpa_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("form_schema_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("filled_questions", sa.Integer(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["form_schema_id"],
            ["public.sage_ai_form_schemas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["public.sage_ai_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_sage_ai_rpa_status_submission_id"),
        "sage_ai_rpa_status",
        ["submission_id"],
        unique=False,
        schema="public",
    )
    op.drop_constraint(
        "sage_ai_form_extractions_form_id_fkey",
        "sage_ai_form_extractions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_form_extractions_submission_id_fkey",
        "sage_ai_form_extractions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_extractions",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_extractions",
        "sage_ai_submission_forms",
        ["form_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_form_schemas_category_id_fkey",
        "sage_ai_form_schemas",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_schemas",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_service_now_tickets_submission_id_fkey",
        "sage_ai_service_now_tickets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_service_now_tickets",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_submission_forms_submission_id_fkey",
        "sage_ai_submission_forms",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_submission_forms_form_schema_id_fkey",
        "sage_ai_submission_forms",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submission_forms",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submission_forms",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_submissions_submitter_id_fkey",
        "sage_ai_submissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_submissions_category_id_fkey",
        "sage_ai_submissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submissions",
        "sage_ai_users",
        ["submitter_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submissions",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_uploaded_documents_submission_id_fkey",
        "sage_ai_uploaded_documents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_uploaded_documents",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "sage_ai_uploaded_documents", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_uploaded_documents_submission_id_fkey",
        "sage_ai_uploaded_documents",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(None, "sage_ai_submissions", schema="public", type_="foreignkey")
    op.drop_constraint(None, "sage_ai_submissions", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "sage_ai_submissions_category_id_fkey",
        "sage_ai_submissions",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_submissions_submitter_id_fkey",
        "sage_ai_submissions",
        "sage_ai_users",
        ["submitter_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_submission_forms", schema="public", type_="foreignkey"
    )
    op.drop_constraint(
        None, "sage_ai_submission_forms", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_submission_forms_form_schema_id_fkey",
        "sage_ai_submission_forms",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_submission_forms_submission_id_fkey",
        "sage_ai_submission_forms",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_service_now_tickets", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_service_now_tickets_submission_id_fkey",
        "sage_ai_service_now_tickets",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_form_schemas", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_form_schemas_category_id_fkey",
        "sage_ai_form_schemas",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_form_extractions", schema="public", type_="foreignkey"
    )
    op.drop_constraint(
        None, "sage_ai_form_extractions", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_form_extractions_submission_id_fkey",
        "sage_ai_form_extractions",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_form_extractions_form_id_fkey",
        "sage_ai_form_extractions",
        "sage_ai_submission_forms",
        ["form_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_public_sage_ai_rpa_status_submission_id"),
        table_name="sage_ai_rpa_status",
        schema="public",
    )
    op.drop_table("sage_ai_rpa_status", schema="public")
    # ### end Alembic commands ###
