"""adding suggestions table

Revision ID: 4f749e445a08
Revises: 1cbe5c612473
Create Date: 2025-11-14 16:19:30.439872

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f749e445a08"
down_revision: Union[str, None] = "1cbe5c612473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sage_ai_suggestions",
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("suggestions", sa.JSON(), nullable=False),
        sa.Column("form_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("question_id"),
        schema="public",
    )
    op.drop_constraint(
        "sage_ai_form_extractions_submission_id_fkey",
        "sage_ai_form_extractions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_form_extractions_form_id_fkey",
        "sage_ai_form_extractions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_extractions",
        "sage_ai_submission_forms",
        ["form_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_extractions",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_form_schemas_category_id_fkey",
        "sage_ai_form_schemas",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_form_schemas",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_rpa_status_submission_id_fkey",
        "sage_ai_rpa_status",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_rpa_status_form_schema_id_fkey",
        "sage_ai_rpa_status",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_rpa_status",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_rpa_status",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_service_now_tickets_submission_id_fkey",
        "sage_ai_service_now_tickets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_service_now_tickets",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_submission_forms_submission_id_fkey",
        "sage_ai_submission_forms",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_submission_forms_form_schema_id_fkey",
        "sage_ai_submission_forms",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submission_forms",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submission_forms",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_submissions_category_id_fkey",
        "sage_ai_submissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sage_ai_submissions_submitter_id_fkey",
        "sage_ai_submissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submissions",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "sage_ai_submissions",
        "sage_ai_users",
        ["submitter_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "sage_ai_uploaded_documents_submission_id_fkey",
        "sage_ai_uploaded_documents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "sage_ai_uploaded_documents",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "sage_ai_uploaded_documents", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_uploaded_documents_submission_id_fkey",
        "sage_ai_uploaded_documents",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(None, "sage_ai_submissions", schema="public", type_="foreignkey")
    op.drop_constraint(None, "sage_ai_submissions", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "sage_ai_submissions_submitter_id_fkey",
        "sage_ai_submissions",
        "sage_ai_users",
        ["submitter_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_submissions_category_id_fkey",
        "sage_ai_submissions",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_submission_forms", schema="public", type_="foreignkey"
    )
    op.drop_constraint(
        None, "sage_ai_submission_forms", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_submission_forms_form_schema_id_fkey",
        "sage_ai_submission_forms",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_submission_forms_submission_id_fkey",
        "sage_ai_submission_forms",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_service_now_tickets", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_service_now_tickets_submission_id_fkey",
        "sage_ai_service_now_tickets",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(None, "sage_ai_rpa_status", schema="public", type_="foreignkey")
    op.drop_constraint(None, "sage_ai_rpa_status", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "sage_ai_rpa_status_form_schema_id_fkey",
        "sage_ai_rpa_status",
        "sage_ai_form_schemas",
        ["form_schema_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_rpa_status_submission_id_fkey",
        "sage_ai_rpa_status",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_form_schemas", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_form_schemas_category_id_fkey",
        "sage_ai_form_schemas",
        "sage_ai_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "sage_ai_form_extractions", schema="public", type_="foreignkey"
    )
    op.drop_constraint(
        None, "sage_ai_form_extractions", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "sage_ai_form_extractions_form_id_fkey",
        "sage_ai_form_extractions",
        "sage_ai_submission_forms",
        ["form_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sage_ai_form_extractions_submission_id_fkey",
        "sage_ai_form_extractions",
        "sage_ai_submissions",
        ["submission_id"],
        ["id"],
    )
    op.drop_table("sage_ai_suggestions", schema="public")
    # ### end Alembic commands ###
