"""move final_score to submission_forms tbl

Revision ID: 61f864674f5f
Revises: 585d12100eef
Create Date: 2025-12-01 22:14:41.301749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f864674f5f'
down_revision: Union[str, None] = '585d12100eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sage_ai_ai_feedback_interaction_id_fkey', 'sage_ai_ai_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_ai_feedback', 'sage_ai_ai_interactions', ['interaction_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('sage_ai_ai_interactions_submission_id_fkey', 'sage_ai_ai_interactions', type_='foreignkey')
    op.drop_constraint('sage_ai_ai_interactions_question_id_fkey', 'sage_ai_ai_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_ai_interactions', 'sage_ai_submission_forms', ['form_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'sage_ai_ai_interactions', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'sage_ai_ai_interactions', 'sage_ai_questions', ['question_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('sage_ai_form_extractions_submission_id_fkey', 'sage_ai_form_extractions', type_='foreignkey')
    op.drop_constraint('sage_ai_form_extractions_form_id_fkey', 'sage_ai_form_extractions', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_form_extractions', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sage_ai_form_extractions', 'sage_ai_submission_forms', ['form_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_form_rules_form_id_fkey', 'sage_ai_form_rules', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_form_rules', 'sage_ai_form_schemas', ['form_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_form_schemas_category_id_fkey', 'sage_ai_form_schemas', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_form_schemas', 'sage_ai_categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_question_scoring_config_question_id_fkey', 'sage_ai_question_scoring_config', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_question_scoring_config', 'sage_ai_questions', ['question_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_rpa_status_form_schema_id_fkey', 'sage_ai_rpa_status', type_='foreignkey')
    op.drop_constraint('sage_ai_rpa_status_submission_id_fkey', 'sage_ai_rpa_status', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_rpa_status', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sage_ai_rpa_status', 'sage_ai_form_schemas', ['form_schema_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_service_now_tickets_submission_id_fkey', 'sage_ai_service_now_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_service_now_tickets', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('sage_ai_submission_forms', sa.Column('final_score', sa.Float(), nullable=True))
    op.drop_constraint('sage_ai_submission_forms_form_schema_id_fkey', 'sage_ai_submission_forms', type_='foreignkey')
    op.drop_constraint('sage_ai_submission_forms_submission_id_fkey', 'sage_ai_submission_forms', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_submission_forms', 'sage_ai_form_schemas', ['form_schema_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sage_ai_submission_forms', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_submission_processing_status_submission_id_fkey', 'sage_ai_submission_processing_status', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_submission_processing_status', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_submissions_submitter_id_fkey', 'sage_ai_submissions', type_='foreignkey')
    op.drop_constraint('sage_ai_submissions_category_id_fkey', 'sage_ai_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_submissions', 'sage_ai_users', ['submitter_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sage_ai_submissions', 'sage_ai_categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('sage_ai_submissions', 'final_score')
    op.drop_constraint('sage_ai_suggestion_coverage_score_question_id_fkey', 'sage_ai_suggestion_coverage_score', type_='foreignkey')
    op.drop_constraint('sage_ai_suggestion_coverage_score_submission_id_fkey', 'sage_ai_suggestion_coverage_score', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_suggestion_coverage_score', 'sage_ai_questions', ['question_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'sage_ai_suggestion_coverage_score', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sage_ai_uploaded_documents_submission_id_fkey', 'sage_ai_uploaded_documents', type_='foreignkey')
    op.create_foreign_key(None, 'sage_ai_uploaded_documents', 'sage_ai_submissions', ['submission_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sage_ai_uploaded_documents', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_uploaded_documents_submission_id_fkey', 'sage_ai_uploaded_documents', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_suggestion_coverage_score', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_suggestion_coverage_score', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_suggestion_coverage_score_submission_id_fkey', 'sage_ai_suggestion_coverage_score', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.create_foreign_key('sage_ai_suggestion_coverage_score_question_id_fkey', 'sage_ai_suggestion_coverage_score', 'sage_ai_questions', ['question_id'], ['id'])
    op.add_column('sage_ai_submissions', sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sage_ai_submissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_submissions', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_submissions_category_id_fkey', 'sage_ai_submissions', 'sage_ai_categories', ['category_id'], ['id'])
    op.create_foreign_key('sage_ai_submissions_submitter_id_fkey', 'sage_ai_submissions', 'sage_ai_users', ['submitter_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_submission_processing_status', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_submission_processing_status_submission_id_fkey', 'sage_ai_submission_processing_status', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_submission_forms', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_submission_forms', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_submission_forms_submission_id_fkey', 'sage_ai_submission_forms', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.create_foreign_key('sage_ai_submission_forms_form_schema_id_fkey', 'sage_ai_submission_forms', 'sage_ai_form_schemas', ['form_schema_id'], ['id'])
    op.drop_column('sage_ai_submission_forms', 'final_score')
    op.drop_constraint(None, 'sage_ai_service_now_tickets', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_service_now_tickets_submission_id_fkey', 'sage_ai_service_now_tickets', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_rpa_status', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_rpa_status', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_rpa_status_submission_id_fkey', 'sage_ai_rpa_status', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.create_foreign_key('sage_ai_rpa_status_form_schema_id_fkey', 'sage_ai_rpa_status', 'sage_ai_form_schemas', ['form_schema_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_question_scoring_config', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_question_scoring_config_question_id_fkey', 'sage_ai_question_scoring_config', 'sage_ai_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_form_schemas', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_form_schemas_category_id_fkey', 'sage_ai_form_schemas', 'sage_ai_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_form_rules', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_form_rules_form_id_fkey', 'sage_ai_form_rules', 'sage_ai_form_schemas', ['form_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_form_extractions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_form_extractions', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_form_extractions_form_id_fkey', 'sage_ai_form_extractions', 'sage_ai_submission_forms', ['form_id'], ['id'])
    op.create_foreign_key('sage_ai_form_extractions_submission_id_fkey', 'sage_ai_form_extractions', 'sage_ai_submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'sage_ai_ai_interactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_ai_interactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sage_ai_ai_interactions', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_ai_interactions_question_id_fkey', 'sage_ai_ai_interactions', 'sage_ai_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('sage_ai_ai_interactions_submission_id_fkey', 'sage_ai_ai_interactions', 'sage_ai_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sage_ai_ai_feedback', schema='public', type_='foreignkey')
    op.create_foreign_key('sage_ai_ai_feedback_interaction_id_fkey', 'sage_ai_ai_feedback', 'sage_ai_ai_interactions', ['interaction_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
