INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES 
    (gen_random_uuid(), 'D-Q01', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'D-Q02', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'D-Q03', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'D-Q04', 5.0, false, NULL, NULL);

INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES
    (gen_random_uuid(), 'L-Q1', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q2', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q3', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q4', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q5', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q6', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q7', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'L-Q8', 5.0, false, NULL, NULL);

INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES
    (gen_random_uuid(), 'AI-Q5', 8.0, true, 0.0, 0.0),
    (gen_random_uuid(), 'AI-Q6', 9.0, true, 0.0, 0.0),
    (gen_random_uuid(), 'AI-Q7', 8.0, true, 0.0, 0.0),
    (gen_random_uuid(), 'AI-Q8', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q9', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q10', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q11', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q12', 6.0, true, 0.0, 0.0),
    (gen_random_uuid(), 'AI-Q13', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q14', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q15', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q16', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q17', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q18', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q19', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q20', 6.0, true, 0.0, 0.0),
    (gen_random_uuid(), 'AI-Q21', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q22', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q23', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q24', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q25', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q26', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q27', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q28', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q29', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q30', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q31', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q32', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q33', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q34', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q35', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q36', 0.0, false, NULL, NULL),
    (gen_random_uuid(), 'AI-Q37', 0.0, false, NULL, NULL);

INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES
    (gen_random_uuid(), 'R-Q1', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q2', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q3', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q4', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q5', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q6', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q7', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q8', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q9', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q10', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q11', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q12', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q13', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q14', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q15', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q16', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q17', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q18', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q19', 1.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q20', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q21', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q22', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q23', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'R-Q24', 5.0, false, NULL, NULL);

INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES
    (gen_random_uuid(), 'S-Q1', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q2', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q3', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q4', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q5', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q6', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q7', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q8', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q9', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q10', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q11', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q12', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q13', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q14', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q15', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'S-Q16', 5.0, false, NULL, NULL);

INSERT INTO public.sage_ai_question_scoring_config (id, question_id, weight, is_mandatory, mandatory_threshold, threshold_penalty)
VALUES
    (gen_random_uuid(), 'W-Q1', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q2', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q3', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q4', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q5', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q6', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q7', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q8', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q9', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q10', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q11', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q12', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q13', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q14', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q15', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q16', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q17', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q18', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q19', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q20', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q21', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q22', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q23', 5.0, false, NULL, NULL),
    (gen_random_uuid(), 'W-Q24', 5.0, false, NULL, NULL);