INSERT INTO public.sage_ai_suggestions (question_id, suggestions, form_type) VALUES
('AI-Q6', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Specify the deployment model (SaaS vendor-hosted, self-hosted within Lilly infrastructure, or hybrid) and indicate if alternative hosting options are available."]', 'ai-registry-form'),
('R-Q6', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the business process or workflow that the AI solution supports."]', 'gco-risk-registry-form'),
('R-Q11', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Explain how the AI solution integrates with existing systems."]', 'gco-risk-registry-form'),
('W-Q3', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the data sources used by the AI solution."]', 'wwtp-form'),
('L-Q5', '["Confirm the data classification level and whether the use case processes any Personal Information (PI), Confidential Information (CI), or only uses public/non-sensitive data (green/yellow classification)."]', 'dlo-form'),
('AI-Q12', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the regulatory requirements applicable to the AI solution."]', 'ai-registry-form'),
('S-Q22', '["Verify that access is restricted exclusively to Lilly workforce (Lilly employees and onboarded contract employees only) unless explicitly approved otherwise."]','security-arch-form'),
('AI-Q20', '["Confirm the data classification level and whether the use case processes any Personal Information (PI), Confidential Information (CI), or only uses public/non-sensitive data (green/yellow classification)."]', 'ai-registry-form'),
('S-Q25', '["Confirm the data classification level and whether the use case processes any Personal Information (PI), Confidential Information (CI), or only uses public/non-sensitive data (green/yellow classification)."]','security-arch-form'),
('AI-Q7', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the key stakeholders for the AI solution."]', 'ai-registry-form'),
('S-Q3', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the data sources used by the AI solution."]', 'security-arch-form'),
('R-Q7', '["Provide a concise 2-3 sentence description of the AI solution covering what it does, its intended business purpose, target users, and whether it is new or enhances existing capability.", "Identify the business process or workflow that the AI solution supports."]', 'gco-risk-registry-form'),
('AI-Q23', '["Verify whether any AI functionality impacts patient safety, product quality, or assists in manufacturing/testing of Lilly products.", "Verify whether the use case has any impact on Lilly patients or customers."]', 'ai-registry-form');